services:
  gaparr:
    image: plexeum/gaparr:latest
    container_name: gaparr
    restart: unless-stopped
    volumes:
      - ./config.json:/app/config.json
      - ./logs:/app/logs
    environment:
      - TZ=America/New_York
      - CRON_SCHEDULE=0 11 * * *