version: '3.8'

services:
  gaparr:
    build: .
    container_name: gaparr
    restart: unless-stopped
    volumes:
      - ./config.json:/app/config.json
      - ./logs:/app/logs
    environment:
      - TZ=America/New_York